# Generated by Django 4.2.4 on 2023-08-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='batch_name',
            field=models.CharField(choices=[('batchA', 'Batch A'), ('batchB', 'Batch B'), ('batchC', 'Batch C')], default='batch1', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='discipline',
            field=models.CharField(max_length=20),
        ),
    ]
