# Generated by Django 4.2.4 on 2023-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0002_alter_category_batch_name_alter_user_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
